esphome:
  name: thv-tv-controller

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "XXXXXXXXXX"

ota:
  password: "XXXXXXXXXX"

wifi:
  power_save_mode: none
  use_address: 192.168.71.15
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  - ssid: !secret wifi_ssid_thv_trs
    password: !secret wifi_password_thv_trs
    manual_ip:
      static_ip: 192.168.71.15
      gateway: 192.168.71.1
      subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "THV-TV-Controller"
    password: "g0bMpzlCsKRb"

captive_portal:
    
remote_transmitter:
  pin: 13
  carrier_duty_percent: 50%

# Individual switches
switch:

  - platform: template
    name: "THV TV Power Toggle"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0xfb04
        command: 0xf708
 

  - platform: template
    name: "THV TV Vol +"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0xfb04
        command: 0xfd02
        

  - platform: template
    name: "THV TV Vol -"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0xfb04
        command: 0xfc03
        
  - platform: template
    name: "Mute"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0xfb04
        command: 0xf609
        
  - platform: template
    name: "THV TV Menu"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0xfb04
        command: 0xbc43
        
  - platform: template
    name: "THV TV Left"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0xfb04
        command: 0xb847
        
  - platform: template
    name: "THV TV Right"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0xfb04
        command: 0xb748
        
  - platform: template
    name: "THV TV Up"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0xfb04
        command: 0xba45
        
  - platform: template
    name: "THV TV Down"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0xfb04
        command: 0xb946
        
  - platform: template
    name: "THV TV OK"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0xfb04
        command: 0xbb44
        
  - platform: template
    name: "THV TV Input"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0xfb04
        command: 0xd02f
        
  - platform: template
    name: "THV TV Exit"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0xfb04
        command: 0xb649
        
sensor:
  - platform: wifi_signal
    id: thv_tv_ir_wifi_signal
    name: "THV TV IR WiFi Signal"
    update_interval: 120s
