esphome:
  name: thv_ir_transmitter
  board: esp32dev
  framework:
    type: arduino
  
# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "XXXXXXXXXX"

wifi:
  fast_connect: true
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
    power_save_mode: none
    manual_ip:
      # Set this to the IP of the ESP
      static_ip: x.x.x.x
      # Set this to the IP address of the router. Often ends with .1
      gateway: x.x.x.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
      subnet: 255.255.255.0


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "THV IR Remote Fallback Hotspot"
    password: "AP-PASSWORD"


captive_portal:
  
remote_transmitter:
  pin: D6
  carrier_duty_percent: 50%

# Individual switches
switch:

  - platform: template
    name: "THV TV Power Toggle"
    optimistic: True
    assumed_state: True
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0x04
        command: 0x08
    turn_off_action:
      remote_transmitter.transmit_nec:
        address: 0x04
        command: 0x08
 

  - platform: template
    name: "THV TV Vol +"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0x04
        command: 0x02
        

  - platform: template
    name: "THV TV Vol -"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0x04
        command: 0x03
        
  - platform: template
    name: "Mute"
    optimistic: True
    assumed_state: True
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0x04
        command: 0x09
        
  - platform: template
    name: "THV TV Menu"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0x04
        command: 0x43
        
  - platform: template
    name: "THV TV Left"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0x04
        command: 0x47
        
  - platform: template
    name: "THV TV Right"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0x04
        command: 0x48
        
  - platform: template
    name: "THV TV Up"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0x04
        command: 0x45
        
  - platform: template
    name: "THV TV Down"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0x04
        command: 0x46
        
  - platform: template
    name: "THV TV OK"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0x04
        command: 0x44
        
  - platform: template
    name: "THV TV Input"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0x04
        command: 0x2F
